name: flutter_flip_flap
description: >
  A customizable split-flap and flip-style display widget for Flutter â€” 
  supports both mechanical "flap" and 3D "flip" animations.
version: 0.3.0
repository: https://github.com/PeterOmbodi/flutter_flip_flap
homepage: https://pub.dev/packages/flutter_flip_flap
issue_tracker: https://github.com/PeterOmbodi/flutter_flip_flap/issues
topics:
  - animation
  - flip
  - split-flap

environment:
  sdk: ^3.9.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
